### ISSUE TITLE
Passing test without actually doing what the lab hopes

### ISSUE THREAD

**Issue by kskilt** [learn-co-curriculum/phrg-dynamic-orm-lab#2]
@garettarrowood 

Hey so you can pass this test without writing a single code in the Super class, just putting everything directly in the student class. I thought I would need to move stuff over at the end, but it just straight passed so thats probably not right

**Comment by garettarrowood** [comment]
I see what you mean. I guess this lab could use another test or two to force code into the respective "Super" and "Child" class.
